# Generated by Django 4.2.7 on 2023-12-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0', max_length=11, null=True, verbose_name='شماره تماس'),
        ),
    ]
