# Generated by Django 4.2.7 on 2023-11-28 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=250)),
                ('type_slug', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='نرخ اجاره ساعتی')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='تاریخ اضافه شدن')),
                ('status', models.BooleanField(default=False, verbose_name='اجاره داده شده')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.type', verbose_name='نوع')),
            ],
            options={
                'verbose_name': 'دوچرخه',
                'verbose_name_plural': 'دورچرخه ها',
            },
        ),
    ]
