# Generated by Django 4.2.7 on 2023-11-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'نوع', 'verbose_name_plural': 'دسته بندی'},
        ),
    ]
