# Generated by Django 4.2.7 on 2023-12-03 06:52

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biketouser',
            name='date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ رزرو'),
        ),
    ]
